# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0003_auto_20170625_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False, 'ordering': ['com_nom']},
        ),
    ]
