# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0007_auto_20170626_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='cod_apoderado',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='fech_act_apod',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='foto_apoderado',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='com_estado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='cod_socio',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='id_profesion',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='log_usuario',
        ),
        migrations.AddField(
            model_name='pago',
            name='id_cuota',
            field=models.ForeignKey(db_column='id_cuota', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Cuota'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='id_pago',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='id_socio',
            field=models.ForeignKey(db_column='id_socio', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Socio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='monto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='id_comuna',
            field=models.ForeignKey(blank=True, db_column='id_comuna', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Comuna'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_ctro_salud',
            field=models.ForeignKey(blank=True, db_column='id_ctro_salud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.CtroSalud'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_est_civil',
            field=models.ForeignKey(blank=True, db_column='id_est_civil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.EstCivil'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_estado',
            field=models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Estado'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_patologia',
            field=models.ForeignKey(blank=True, db_column='id_patologia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Patologia'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_prev',
            field=models.ForeignKey(blank=True, db_column='id_prev', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Prevision'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_salud',
            field=models.ForeignKey(blank=True, db_column='id_salud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Salud'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_tipo_paciente',
            field=models.ForeignKey(blank=True, db_column='id_tipo_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.TipoPaciente'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='comuna_numero',
            field=models.ForeignKey(blank=True, db_column='comuna_numero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Comuna'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='id_socio',
            field=models.ForeignKey(blank=True, db_column='id_socio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Socio'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='provincia_prov_cod',
            field=models.ForeignKey(db_column='provincia_prov_cod', on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Provincia'),
        ),
        migrations.AlterField(
            model_name='ctrosalud',
            name='comuna_numero',
            field=models.ForeignKey(blank=True, db_column='comuna_numero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Comuna'),
        ),
        migrations.AlterField(
            model_name='ctrosalud',
            name='id_ctro_salud',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_emision',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='id_estado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patologia',
            name='id_patologia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prevision',
            name='id_prevision',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='region_region_numero',
            field=models.ForeignKey(db_column='region_region_numero', on_delete=django.db.models.deletion.DO_NOTHING, to='sas.Region'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='id_salud',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id_socio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipopaciente',
            name='id_tipo_pacientes',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='apoderado',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comuna',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ctrosalud',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cuota',
            table=None,
        ),
        migrations.AlterModelTable(
            name='estado',
            table=None,
        ),
        migrations.AlterModelTable(
            name='estcivil',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pago',
            table=None,
        ),
        migrations.AlterModelTable(
            name='patologia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prevision',
            table=None,
        ),
        migrations.AlterModelTable(
            name='provincia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='region',
            table=None,
        ),
        migrations.AlterModelTable(
            name='salud',
            table=None,
        ),
        migrations.AlterModelTable(
            name='socio',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipopaciente',
            table=None,
        ),
    ]
