# Generated by Django 2.0.dev20170514183117 on 2017-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('cod_apoderado', models.CharField(blank=True, max_length=15, null=True)),
                ('rut_apoderado', models.CharField(blank=True, max_length=10, null=True)),
                ('nom_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_pat_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_mat_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('email_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('telef_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_nac_apoderado', models.DateField(blank=True, null=True)),
                ('foto_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('comuna_numero', models.IntegerField(blank=True, null=True)),
                ('dir_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_ing_apod', models.DateField(blank=True, null=True)),
                ('id_socio', models.IntegerField(blank=True, null=True)),
                ('fech_act_apod', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apoderado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloqueosTomaHoras',
            fields=[
                ('id_bloqueo', models.AutoField(primary_key=True, serialize=False)),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('tratante', models.IntegerField()),
                ('comentario', models.TextField()),
            ],
            options={
                'db_table': 'bloqueos_toma_horas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitacionTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt1', models.TextField()),
                ('txt2', models.TextField()),
                ('txt3', models.TextField()),
                ('txt4', models.TextField()),
            ],
            options={
                'db_table': 'citacion_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciu_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('reg_cod', models.IntegerField()),
                ('ciu_nombre', models.TextField()),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('com_cod', models.AutoField(primary_key=True, serialize=False)),
                ('reg_cod', models.IntegerField()),
                ('com_nom', models.TextField()),
            ],
            options={
                'db_table': 'comunas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtroSalud',
            fields=[
                ('id_ctro_salud', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('dir_ctro_salud', models.CharField(blank=True, max_length=60, null=True)),
                ('rut_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('comuna_numero', models.IntegerField(blank=True, null=True)),
                ('telef_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('email_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('med_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('enf_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ctro_salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_especialidad', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id_especialista', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_especialista', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_pat_especialista', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_mat_especialista', models.CharField(blank=True, max_length=45, null=True)),
                ('email_especialista', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'especialista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_estado', models.CharField(max_length=45)),
                ('com_estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstCivil',
            fields=[
                ('id_est_civil', models.AutoField(primary_key=True, serialize=False)),
                ('nom_est_civil', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'est_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogMovSocios',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_usuario', models.IntegerField(blank=True, null=True)),
                ('log_fecha', models.DateField(blank=True, null=True)),
                ('log_id_socios', models.IntegerField()),
                ('log_cod_socios', models.CharField(blank=True, max_length=15, null=True)),
                ('log_rut_socios', models.CharField(blank=True, max_length=10, null=True)),
                ('log_sexo_socios', models.CharField(blank=True, max_length=1, null=True)),
                ('log_nom_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('log_apel_pat_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('log_apel_mat_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('log_dir_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('log_email_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('log_telef_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('log_cel_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('log_fech_nac_socios', models.DateField(blank=True, null=True)),
                ('log_foto_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('log_region_numero', models.IntegerField(blank=True, null=True)),
                ('log_ciudad_numero', models.IntegerField(blank=True, null=True)),
                ('log_comuna_numero', models.IntegerField(blank=True, null=True)),
                ('log_fech_ing_socios', models.DateField(blank=True, null=True)),
                ('log_id_estado', models.IntegerField(blank=True, null=True)),
                ('log_id_est_civil', models.IntegerField(blank=True, null=True)),
                ('log_id_profesion', models.IntegerField(blank=True, null=True)),
                ('log_id_salud', models.IntegerField(blank=True, null=True)),
                ('log_id_ctro_salud', models.IntegerField(blank=True, null=True)),
                ('log_id_prev', models.IntegerField(blank=True, null=True)),
                ('log_id_perf', models.IntegerField(blank=True, null=True)),
                ('log_id_patologia', models.IntegerField(blank=True, null=True)),
                ('log_id_apoderado', models.IntegerField(blank=True, null=True)),
                ('log_id_tipo_paciente', models.IntegerField(blank=True, null=True)),
                ('log_fech_actu', models.DateField(blank=True, null=True)),
                ('log_usuario_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_mov_socios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovSocio',
            fields=[
                ('mov_id', models.AutoField(primary_key=True, serialize=False)),
                ('mov_id_tipo', models.IntegerField()),
                ('mov_tipo', models.CharField(max_length=50)),
                ('mov_fecha', models.DateField()),
                ('mov_rut_socio', models.CharField(max_length=12)),
                ('mov_user', models.IntegerField()),
            ],
            options={
                'db_table': 'mov_socio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id_patologia', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_patologia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'patologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_perf', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_perf', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfpriv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perf', models.IntegerField()),
                ('id_priv', models.IntegerField()),
            ],
            options={
                'db_table': 'perfpriv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_perm', models.AutoField(primary_key=True, serialize=False)),
                ('menu_perm', models.TextField()),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id_prevision', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_prevision', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'prevision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privilegios',
            fields=[
                ('id_priv', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_priv', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'privilegios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id_profesion', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_profesion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'profesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('region_numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.TextField()),
            ],
            options={
                'db_table': 'regiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id_salud', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_salud', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id_socios', models.AutoField(primary_key=True, serialize=False)),
                ('cod_socios', models.CharField(blank=True, max_length=15, null=True)),
                ('rut_socios', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo_socios', models.CharField(blank=True, max_length=1, null=True)),
                ('nom_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_pat_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_mat_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('dir_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('email_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('telef_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('cel_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_nac_socios', models.DateField(blank=True, null=True)),
                ('foto_socios', models.CharField(blank=True, max_length=45, null=True)),
                ('region_numero', models.IntegerField(blank=True, null=True)),
                ('comuna_numero', models.IntegerField(blank=True, null=True)),
                ('fech_ing_socios', models.DateField(blank=True, null=True)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_est_civil', models.IntegerField(blank=True, null=True)),
                ('id_profesion', models.IntegerField(blank=True, null=True)),
                ('id_salud', models.IntegerField(blank=True, null=True)),
                ('id_ctro_salud', models.IntegerField(blank=True, null=True)),
                ('id_prev', models.IntegerField(blank=True, null=True)),
                ('id_perf', models.IntegerField(blank=True, null=True)),
                ('id_patologia', models.IntegerField(blank=True, null=True)),
                ('id_apoderado', models.IntegerField(blank=True, null=True)),
                ('id_tipo_paciente', models.IntegerField(blank=True, null=True)),
                ('fech_actu', models.DateTimeField(blank=True, null=True)),
                ('log_usuario', models.IntegerField(blank=True, null=True)),
                ('ciudad_numero', models.IntegerField(blank=True, null=True)),
                ('fech_defun', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPacientes',
            fields=[
                ('id_tipo_pacientes', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_tipo_pacientes', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TomaHoras',
            fields=[
                ('id_toma_horas', models.AutoField(primary_key=True, serialize=False)),
                ('id_socios', models.IntegerField(blank=True, null=True)),
                ('fecha_toma_horas', models.DateField(blank=True, null=True)),
                ('hora_toma_hora', models.CharField(max_length=100)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('com_toma_horas', models.CharField(blank=True, max_length=200, null=True)),
                ('id_centro', models.IntegerField(blank=True, null=True)),
                ('id_especialista', models.IntegerField(blank=True, null=True)),
                ('estado_hora', models.IntegerField()),
            ],
            options={
                'db_table': 'toma_horas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('id_perfil', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
