# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('rut_apoderado', models.CharField(blank=True, max_length=10, null=True)),
                ('nom_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_pat_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_mat_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('email_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('telef_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_nac_apoderado', models.DateField(blank=True, null=True)),
                ('dir_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_ing_apod', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apoderado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('com_cod', models.AutoField(primary_key=True, serialize=False)),
                ('com_nom', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'comuna',
                'ordering': ['com_nom'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtroSalud',
            fields=[
                ('id_ctro_salud', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('dir_ctro_salud', models.CharField(blank=True, max_length=60, null=True)),
                ('rut_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('telef_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('email_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('med_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('enf_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Centros de Salud',
                'db_table': 'ctro_salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
            ],
            options={
                'db_table': 'cuota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nom_estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado',
                'ordering': ['nom_estado'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstCivil',
            fields=[
                ('id_est_civil', models.AutoField(primary_key=True, serialize=False)),
                ('nom_est_civil', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estados Civiles',
                'db_table': 'est_civil',
                'ordering': ['nom_est_civil'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha_pago', models.DateField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id_patologia', models.AutoField(primary_key=True, serialize=False)),
                ('nom_patologia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'patologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id_prevision', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prevision', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Previsiones',
                'db_table': 'prevision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('prov_cod', models.AutoField(primary_key=True, serialize=False)),
                ('prov_nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id_salud', models.AutoField(primary_key=True, serialize=False)),
                ('nom_salud', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Salud',
                'db_table': 'salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.AutoField(primary_key=True, serialize=False)),
                ('rut_socio', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo_socio', models.CharField(blank=True, max_length=1, null=True)),
                ('nom_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_pat_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_mat_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('dir_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('email_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('telef_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('cel_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_nac_socio', models.DateField(blank=True, null=True)),
                ('foto_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_ing_socio', models.DateField(blank=True, null=True)),
                ('fech_defun', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPaciente',
            fields=[
                ('id_tipo_pacientes', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_pacientes', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Pacientes',
                'db_table': 'tipo_paciente',
                'managed': False,
            },
        ),
    ]
