# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_apoderado', models.CharField(blank=True, max_length=10, null=True)),
                ('nom_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_pat_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_mat_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('email_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('telef_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_nac_apoderado', models.DateField(blank=True, null=True)),
                ('dir_apoderado', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_ing_apod', models.DateField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_nom', models.CharField(max_length=45)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['com_nom'],
            },
        ),
        migrations.CreateModel(
            name='CtroSalud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('dir_ctro_salud', models.CharField(blank=True, max_length=60, null=True)),
                ('rut_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('telef_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('email_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('med_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('enf_ctro_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('comuna_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Comuna')),
            ],
            options={
                'verbose_name_plural': 'Centros de Salud',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_estado', models.CharField(max_length=45)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom_estado'],
            },
        ),
        migrations.CreateModel(
            name='EstCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_est_civil', models.CharField(blank=True, max_length=45, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Estados Civiles',
                'ordering': ['nom_est_civil'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('id_cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Cuota')),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patologia', models.CharField(max_length=45)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prevision', models.CharField(blank=True, max_length=45, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Previsiones',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_nombre', models.CharField(max_length=45)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=45)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salud', models.CharField(blank=True, max_length=45, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Salud',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_socio', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo_socio', models.CharField(blank=True, max_length=1, null=True)),
                ('nom_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_pat_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_mat_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('dir_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('email_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('telef_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('cel_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_nac_socio', models.DateField(blank=True, null=True)),
                ('foto_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_ing_socio', models.DateField(blank=True, null=True)),
                ('fech_defun', models.DateField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Comuna')),
                ('id_ctro_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.CtroSalud')),
                ('id_est_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sas.EstCivil')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Estado')),
                ('id_patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Patologia')),
                ('id_prev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Prevision')),
                ('id_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sas.Salud')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo_pacientes', models.CharField(blank=True, max_length=45, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Pacientes',
            },
        ),
        migrations.AddField(
            model_name='socio',
            name='id_tipo_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.TipoPaciente'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region_region_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Region'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Socio'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia_prov_cod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Provincia'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='comuna_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Comuna'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='id_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.Socio'),
        ),
    ]
