# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('com_cod', models.AutoField(primary_key=True, serialize=False)),
                ('com_nom', models.CharField(max_length=45)),
                ('provincia_prov_cod', models.IntegerField()),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('prov_cod', models.AutoField(primary_key=True, serialize=False)),
                ('prov_nombre', models.CharField(max_length=45)),
                ('region_region_numero', models.IntegerField()),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_socio', models.CharField(blank=True, max_length=15, null=True)),
                ('rut_socio', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo_socio', models.CharField(blank=True, max_length=1, null=True)),
                ('nom_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_pat_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_mat_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('dir_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('email_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('telef_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('cel_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_nac_socio', models.DateField(blank=True, null=True)),
                ('foto_socio', models.CharField(blank=True, max_length=45, null=True)),
                ('fech_ing_socio', models.DateField(blank=True, null=True)),
                ('id_profesion', models.IntegerField(blank=True, null=True)),
                ('log_usuario', models.IntegerField(blank=True, null=True)),
                ('fech_defun', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPaciente',
            fields=[
                ('id_tipo_pacientes', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_tipo_pacientes', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_paciente',
                'managed': False,
            },
        ),
    ]
