# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0002_comuna_cuota_provincia_region_socio_tipopaciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': False, 'ordering': ['nom_estado']},
        ),
        migrations.AlterModelOptions(
            name='estcivil',
            options={'managed': False, 'ordering': ['nom_est_civil']},
        ),
    ]
