# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0005_auto_20170625_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
    ]
